from __future__ import annotations

import pandas as pd
import pytest

from src.research.direction_phase import (
    DEFAULT_CANDIDATES,
    adx_directional_gated,
    adx_directional_raw,
    ema_compare,
    ema_compare_slow,
    evaluate_direction_candidate,
    market_structure_bias,
    run_direction_phase,
    supertrend_direction,
)
from src.research.signal_evaluator import compute_forward_targets
from tests.fixtures.ohlcv import make_sample_ohlcv


@pytest.fixture
def df_with_targets() -> pd.DataFrame:
    # Enough bars for every candidate's min-data requirement (market structure
    # needs 4*pivot_bars+1 = 21; supertrend/adx need 2*period = 28).
    df = make_sample_ohlcv(bars=200)
    return compute_forward_targets(df, horizons=(4, 8))


def test_ema_compare_matches_manual_ema_cross(df_with_targets: pd.DataFrame) -> None:
    signal = ema_compare(df_with_targets)
    fast = df_with_targets["close"].ewm(span=12, adjust=False).mean()
    slow = df_with_targets["close"].ewm(span=26, adjust=False).mean()
    expected_up = fast > slow
    assert ((signal == "UP") == expected_up).all()


def test_ema_compare_slow_uses_50_200(df_with_targets: pd.DataFrame) -> None:
    signal = ema_compare_slow(df_with_targets)
    fast = df_with_targets["close"].ewm(span=50, adjust=False).mean()
    slow = df_with_targets["close"].ewm(span=200, adjust=False).mean()
    expected_up = fast > slow
    assert ((signal == "UP") == expected_up).all()


def test_all_default_candidates_produce_up_down_only(df_with_targets: pd.DataFrame) -> None:
    for name, fn in DEFAULT_CANDIDATES.items():
        signal = fn(df_with_targets)
        assert set(signal.unique()) <= {"UP", "DOWN"}, f"{name} produced unexpected labels"
        assert len(signal) == len(df_with_targets)


def test_supertrend_direction_is_deterministic(df_with_targets: pd.DataFrame) -> None:
    first = supertrend_direction(df_with_targets)
    second = supertrend_direction(df_with_targets)
    assert first.equals(second)


def test_adx_directional_gated_holds_over_when_weak(df_with_targets: pd.DataFrame) -> None:
    """With an absurdly high min_adx, the gate should never see ADX >= threshold
    after the first bar, so the signal must stay constant from bar 1 onward.
    """
    gated = adx_directional_gated(df_with_targets, min_adx=999.0)
    assert (gated.iloc[1:] == gated.iloc[1]).all()


def test_adx_gated_has_fewer_or_equal_flips_than_raw(df_with_targets: pd.DataFrame) -> None:
    raw = adx_directional_raw(df_with_targets)
    gated = adx_directional_gated(df_with_targets)
    raw_flips = int((raw != raw.shift(1)).sum())
    gated_flips = int((gated != gated.shift(1)).sum())
    assert gated_flips <= raw_flips


def test_market_structure_bias_matches_scalar_helper_at_a_fixed_bar() -> None:
    """The vectorized bias series must agree with the production scalar helper
    (`_market_structure_latest`) when evaluated at the same historical point —
    this is the guard against the vectorized rewrite silently diverging from
    what a real provider computes.
    """
    from src.features.indicators.market_structure import _market_structure_latest

    df = make_sample_ohlcv(bars=200)
    series = market_structure_bias(df, pivot_bars=5)

    # Pick a bar comfortably inside the history so both methods have identical
    # visibility into confirmed pivots up to that point.
    t = 150
    scalar_bias, _bos = _market_structure_latest(df.iloc[: t + 1], pivot_bars=5)
    expected_label = "UP" if scalar_bias >= 0 else "DOWN"
    assert series.iloc[t] == expected_label


def test_evaluate_direction_candidate_accuracy_is_between_0_and_100(
    df_with_targets: pd.DataFrame,
) -> None:
    signal = ema_compare(df_with_targets)
    accuracy, flips, median_run_len = evaluate_direction_candidate(
        df_with_targets, signal, horizons=(4, 8)
    )
    for h, acc in accuracy.items():
        assert 0.0 <= acc <= 100.0
    assert flips >= 0
    assert median_run_len >= 1.0


def test_run_direction_phase_returns_one_result_per_candidate(
    df_with_targets: pd.DataFrame,
) -> None:
    results = run_direction_phase(df_with_targets, horizons=(4, 8))
    assert len(results) == len(DEFAULT_CANDIDATES)
    names = {r.name for r in results}
    assert names == set(DEFAULT_CANDIDATES.keys())


def test_random_walk_signal_does_not_pass_threshold_by_default() -> None:
    """A signal generated by the platform's own EMA-cross logic on synthetic
    random-walk data should not spuriously pass the edge threshold — guards
    against an overly loose PASS_MARGIN_PCT/PASS_MIN_HORIZONS default.
    """
    df = make_sample_ohlcv(bars=300, seed=7)
    df_with_targets = compute_forward_targets(df, horizons=(4, 8, 14, 24))
    results = run_direction_phase(
        df_with_targets, candidates={"ema": ema_compare}, horizons=(4, 8, 14, 24)
    )
    assert len(results) == 1
    # Not a hard guarantee for any possible seed, but true for this fixture's
    # RNG-driven random walk, and documents the intended behavior.
    assert results[0].passes_threshold is False
